
import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author albertoramlop
 */
public class JFrameTrivial extends javax.swing.JFrame {

    DataOutputStream a;
    DataInputStream entrada;
    int Tiempo;
    boolean end;

    public JFrameTrivial() {
        initComponents();
        inicio();
    }

    public void inicio() {
        try {
            Socket clientSocket = new Socket();
            InetSocketAddress addr = new InetSocketAddress("172.17.129.223", 5555);
            clientSocket.connect(addr);
            a = new DataOutputStream(clientSocket.getOutputStream());
            entrada = new DataInputStream(clientSocket.getInputStream());
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameCategorias = new javax.swing.JFrame();
        tb_cultura = new javax.swing.JLabel();
        tb_deportes = new javax.swing.JLabel();
        tb_Historia = new javax.swing.JLabel();
        tb_Ciencias = new javax.swing.JLabel();
        bt_ciencia = new javax.swing.JButton();
        bt_historia = new javax.swing.JButton();
        bt_deportes = new javax.swing.JButton();
        bt_cultura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFramePreguntas = new javax.swing.JFrame();
        bt_resp1 = new javax.swing.JButton();
        bt_resp4 = new javax.swing.JButton();
        bt_resp2 = new javax.swing.JButton();
        bt_resp3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label_Pregunta = new javax.swing.JLabel();
        tiemmpo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nick_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jFrameCategorias.setMinimumSize(new java.awt.Dimension(723, 468));
        jFrameCategorias.setPreferredSize(new java.awt.Dimension(723, 468));
        jFrameCategorias.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_cultura.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tb_cultura.setText("0/2");
        jFrameCategorias.getContentPane().add(tb_cultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        tb_deportes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tb_deportes.setText("0/2");
        jFrameCategorias.getContentPane().add(tb_deportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        tb_Historia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tb_Historia.setText("0/2");
        jFrameCategorias.getContentPane().add(tb_Historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        tb_Ciencias.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tb_Ciencias.setText("0/2");
        jFrameCategorias.getContentPane().add(tb_Ciencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        bt_ciencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\chemistry.png")); // NOI18N
        bt_ciencia.setName("ciencia"); // NOI18N
        bt_ciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historiaActionPerformed(evt);
            }
        });
        jFrameCategorias.getContentPane().add(bt_ciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 110, 90));

        bt_historia.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\history.png")); // NOI18N
        bt_historia.setName("historia"); // NOI18N
        bt_historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historiaActionPerformed(evt);
            }
        });
        jFrameCategorias.getContentPane().add(bt_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 110, 90));

        bt_deportes.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\football.png")); // NOI18N
        bt_deportes.setName("deportes"); // NOI18N
        bt_deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historiaActionPerformed(evt);
            }
        });
        jFrameCategorias.getContentPane().add(bt_deportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 110, 90));

        bt_cultura.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\geography.png")); // NOI18N
        bt_cultura.setName("cultura"); // NOI18N
        bt_cultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historiaActionPerformed(evt);
            }
        });
        jFrameCategorias.getContentPane().add(bt_cultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\categorias.jpg")); // NOI18N
        jFrameCategorias.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        jFramePreguntas.setMinimumSize(new java.awt.Dimension(723, 468));
        jFramePreguntas.setPreferredSize(new java.awt.Dimension(723, 468));
        jFramePreguntas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_resp1.setBackground(new java.awt.Color(255, 255, 255));
        bt_resp1.setName("ciencia"); // NOI18N
        bt_resp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resp2bt_historiaActionPerformed(evt);
            }
        });
        jFramePreguntas.getContentPane().add(bt_resp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 220, 40));

        bt_resp4.setBackground(new java.awt.Color(255, 255, 255));
        bt_resp4.setName("historia"); // NOI18N
        bt_resp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resp2bt_historiaActionPerformed(evt);
            }
        });
        jFramePreguntas.getContentPane().add(bt_resp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 220, 40));

        bt_resp2.setBackground(new java.awt.Color(255, 255, 255));
        bt_resp2.setName("deportes"); // NOI18N
        bt_resp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resp2bt_historiaActionPerformed(evt);
            }
        });
        jFramePreguntas.getContentPane().add(bt_resp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 220, 40));

        bt_resp3.setBackground(new java.awt.Color(255, 255, 255));
        bt_resp3.setName("cultura"); // NOI18N
        bt_resp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resp2bt_historiaActionPerformed(evt);
            }
        });
        jFramePreguntas.getContentPane().add(bt_resp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 220, 40));

        jButton3.setText("ATRÁS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFramePreguntas.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        label_Pregunta.setBackground(new java.awt.Color(51, 51, 255));
        label_Pregunta.setFont(new java.awt.Font("ITC Avant Garde Std Md", 0, 12)); // NOI18N
        label_Pregunta.setForeground(new java.awt.Color(255, 255, 255));
        label_Pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Pregunta.setText("dfgsdgdgdfgdfgdfgdfgdfgdfgdfgonjonsognaasonvnfsoifdnfgpi ???");
        jFramePreguntas.getContentPane().add(label_Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 630, 40));

        tiemmpo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tiemmpo.setForeground(new java.awt.Color(255, 0, 51));
        tiemmpo.setText("20");
        jFramePreguntas.getContentPane().add(tiemmpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\preguntas.jpg")); // NOI18N
        jFramePreguntas.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("ITC Avant Garde Std Md", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 70, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("ITC Avant Garde Std Md", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("JUGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 142, 34));
        getContentPane().add(nick_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\albertoramlop\\Desktop\\OneDrive - Centre d'Estudis Monlau\\2o DAM\\M9 - PROGRAMACIÓN DE SERVICIOS Y PROCESOS\\juegoTrivial\\fondoinicio.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = nick_name.getText();
        try {
            a.writeUTF(name);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTrivial.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setVisible(false);
        jFrameCategorias.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historiaActionPerformed

        jFrameCategorias.dispose();
        try {
            JButton btn = (JButton) evt.getSource();
            String msj = "";
            switch (btn.getName()) {
                case "ciencia":
                    msj = "0";
                    break;
                case "historia":
                    msj = "1";
                    break;
                case "cultura":
                    msj = "2";
                    break;
                case "deportes":
                    msj = "3";
                    break;
            }
            a.writeUTF(msj);
            String txt = entrada.readUTF();
            DataClass.PreguntaA = new Pregunta().toObj(txt);
            label_Pregunta.setText(DataClass.PreguntaA.getPregunta());
            System.out.println(getnumrandom());
        switch(getnumrandom()){
           case 1:
               bt_resp1.setText(DataClass.PreguntaA.getResp_Ko1());
               bt_resp2.setText(DataClass.PreguntaA.getResp_Ko2());
               bt_resp3.setText(DataClass.PreguntaA.getResp_Ko3());
               bt_resp4.setText(DataClass.PreguntaA.getResp_Ok());
               break;
           case 2:
               bt_resp1.setText(DataClass.PreguntaA.getResp_Ok());
               bt_resp2.setText(DataClass.PreguntaA.getResp_Ko2());
               bt_resp3.setText(DataClass.PreguntaA.getResp_Ko3());
               bt_resp4.setText(DataClass.PreguntaA.getResp_Ko1());
               break;
           case 3:
               bt_resp1.setText(DataClass.PreguntaA.getResp_Ko1());
               bt_resp2.setText(DataClass.PreguntaA.getResp_Ok());
               bt_resp3.setText(DataClass.PreguntaA.getResp_Ko3());
               bt_resp4.setText(DataClass.PreguntaA.getResp_Ko2());
               break;
           case 4:
               bt_resp1.setText(DataClass.PreguntaA.getResp_Ko1());
               bt_resp2.setText(DataClass.PreguntaA.getResp_Ko2());
               bt_resp3.setText(DataClass.PreguntaA.getResp_Ok());
               bt_resp4.setText(DataClass.PreguntaA.getResp_Ko3());
               break;
       }
            Tiempo = 20;
        Timer a = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    tiemmpo.setText(Tiempo + "");
                    Tiempo--;
                    if(Tiempo <= 0){
                        JOptionPane.showMessageDialog(null, "Ha terminado el tiempo");
                        jFramePreguntas.dispose();
                        jFrameCategorias.setVisible(true);
                        Re();
                        ((Timer)e.getSource()).stop();
                    }
                }
            });
            a.start();   

            jFramePreguntas.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTrivial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bt_historiaActionPerformed

    private void bt_resp2bt_historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resp2bt_historiaActionPerformed
        JButton btn = (JButton) evt.getSource();
        if(btn.getText().equals(DataClass.PreguntaA.getResp_Ok())){
            btn.setBackground(Color.green);
            JOptionPane.showMessageDialog(null, "Respuesta Correcta");

        switch(DataClass.PreguntaA.getCategoria()){
           case "Ciencias":
               DataClass.Ciencia++;
                break;
            case "Historia":
                DataClass.Historia++;
                break;
            case "Cultura":
                DataClass.Cultura++;
                break;
            case "Deportes":
                DataClass.Deportes++;
                break;
            }
        }else{
          btn.setBackground(Color.red);
        JOptionPane.showMessageDialog(null, "Respuesta Incorrecta");
        }
        jFramePreguntas.dispose();
        jFrameCategorias.setVisible(true);
        Re();
    }//GEN-LAST:event_bt_resp2bt_historiaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jFramePreguntas.dispose();
       jFrameCategorias.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTrivial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTrivial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTrivial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTrivial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTrivial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ciencia;
    private javax.swing.JButton bt_cultura;
    private javax.swing.JButton bt_deportes;
    private javax.swing.JButton bt_historia;
    private javax.swing.JButton bt_resp1;
    private javax.swing.JButton bt_resp2;
    private javax.swing.JButton bt_resp3;
    private javax.swing.JButton bt_resp4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrameCategorias;
    private javax.swing.JFrame jFramePreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel label_Pregunta;
    private javax.swing.JTextField nick_name;
    private javax.swing.JLabel tb_Ciencias;
    private javax.swing.JLabel tb_Historia;
    private javax.swing.JLabel tb_cultura;
    private javax.swing.JLabel tb_deportes;
    private javax.swing.JLabel tiemmpo;
    // End of variables declaration//GEN-END:variables
    
    public void Re(){
        if(DataClass.Ciencia == 2){
            bt_ciencia.setEnabled(false);
        }
        if(DataClass.Cultura == 2){
            bt_cultura.setEnabled(false);
        }
        if(DataClass.Deportes == 2){
            bt_deportes.setEnabled(false);
        }
        if(DataClass.Historia == 2){
            bt_historia.setEnabled(false);
        }
        UpdateCat();
        bt_resp1.setBackground(Color.WHITE);
        bt_resp2.setBackground(Color.WHITE);
        bt_resp3.setBackground(Color.WHITE);
        bt_resp4.setBackground(Color.WHITE);
       if(DataClass.Ciencia == 2 && DataClass.Cultura == 2 && DataClass.Deportes == 2 && DataClass.Historia == 2){
           JOptionPane.showMessageDialog(null, "Has Ganado!!");
           System.exit(0);
       }
    }
    
    public void UpdateCat(){
        tb_Ciencias.setText(DataClass.Ciencia + "/2");
        tb_Historia.setText(DataClass.Historia + "/2");
        tb_cultura.setText(DataClass.Cultura + "/2");
        tb_deportes.setText(DataClass.Deportes + "/2");
    }
    
    public int getnumrandom(){
       return (int) (Math.random() * 4) + 1;
   }
}
